name: Build and Artifact the ESP-IDF Project

permissions:
  contents: write

on:
  push:
    tags:
     - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Generate unique name
      id: generate_name
      uses: francisfuzz/name-generator@v1
      with:
        prefix: 'release-'
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ steps.generate_name.outputs.name }}
        draft: false
        prerelease: false
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32c3
        path: './'
    - name: Upload Bootloader Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/bootloader/bootloader.bin
        asset_name: bootloader.bin
        asset_content_type: application/octet-stream
    - name: Upload Partition Table Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/partition_table/partition-table.bin
        asset_name: partition-table.bin
        asset_content_type: application/octet-stream
    - name: Upload OTA Data Initial Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/ota_data_initial.bin
        asset_name: ota_data_initial.bin
        asset_content_type: application/octet-stream
    - name: Upload Wican FW Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/wican-fw_v171_hv300.bin
        asset_name: wican-fw_v171_hv300.bin
        asset_content_type: application/octet-stream
